### PR TITLE
Upgrade mongoose v5 and outdated packages

### PR DESCRIPTION
**Pull request by thedv91**
- Support mongoose v5
- Expose field name config of the schema
- Upgrade babel to v7
- Upgrade outdated packages

### CODE REVIEW

**Comment by Haroenv** [comment]
thanks, this is definitely appreciated!

**Comment by realmike33** [comment]
is this going to be merged any time soon?

**Comment by Haroenv** [comment]
It needs to be tested out, and so far I haven’t been able to find someone who has a mongoose app running at Algolia, so I don’t want to merge untested code like this. Did you try it out?

**Comment by Ivraj** [comment]
Hi, I was wondering if there was any progress on testing this PR? 

If it's the case that this code needs to be tested with actual mongoose apps, maybe we could have an alpha or beta version that people can use and give feedback on?

**Pull request closed without merging**
